# Generated by Django 2.1.7 on 2019-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragmenting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('fragment_data', models.TextField()),
            ],
        ),
    ]
