# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-03 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fragmenting', '0002_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 3, 5, 44, 18, 121341, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 3, 3, 5, 44, 27, 370513, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
